name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v6

      - name: Setup CI env and Run tests
        run: npm ci && npm run test

      - name: Debug secret
        run: |
          echo "Longitud del secreto: ${#SECRET}"
        env:
          SECRET: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Get short Gir commit SHA
      #   id: vars
      #   run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push image
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/docker-react:${{ github.sha }} .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/docker-react:${{ github.sha }}

      - name: Deploy to Azure Container Instances
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/docker-react:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: aci-docker-react
          location: 'brazilsouth'
